---
VALIDATE_ALL_CODEBASE: true
FLAVOR_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true
LOG_LEVEL: WARNING

DISABLE:
  - SPELL

DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_TRUFFLEHOG

BASH_FILTER_REGEX_EXCLUDE: "gradlew"
SHELL_FILTER_REGEX_EXCLUDE: ".github/workflows"

DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3007"
