---
# MegaLinter Configuration
VALIDATE_ALL_CODEBASE: true
FLAVOR_SUGGESTIONS: false

DISABLE:
  - SPELL

DISABLE_LINTER:
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_TRUFFLEHOG

# Bash linting excludes
BASH_SHELLCHECK_FILTER_REGEX_EXCLUDE: "gradlew"
BASH_SHFMT_FILTER_REGEX_EXCLUDE: "gradlew"

# Trivy extra settings
REPOSITORY_TRIVY_SKIP_INIT: true
DOCKERFILE_TRIVY: off
