---
VALIDATE_ALL_CODEBASE: true
FLAVOR_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true

DISABLE:
  - BASH

DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_TRUFFLEHOG

DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3007"
