FROM gradle:jdk21 AS build
WORKDIR /app
COPY . /app
RUN ./gradlew build --no-daemon

FROM aquasec/trivy:latest AS sbom
WORKDIR /app
COPY --from=build /app/build/libs/*-all.jar app.jar
RUN trivy fs --format spdx-json --output /app/sbom.spdx.json /app/app.jar

FROM gcr.io/projectsigstore/cosign:latest AS cosign
ENV COSIGN_EXPERIMENTAL=1
WORKDIR /app
COPY --from=build /app/build/libs/*-all.jar app.jar
COPY --from=sbom /app/sbom.spdx.json /app/sbom.spdx.json
RUN cosign sign-blob --yes \
      --output-signature=app.jar.sig \
      app.jar

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=cosign /app/app.jar app.jar
COPY --from=cosign /app/app.jar.sig app.jar.sig
COPY --from=sbom /app/sbom.spdx.json /app/sbom.spdx.json
RUN groupadd -r Kepler && useradd -r -g Kepler Kepler
RUN chown -R Kepler:Kepler /app
USER Kepler
ENTRYPOINT ["java", "-jar", "app.jar"]
